In [1]:
import numpy as np


In [11]:
#requires curve and ssquare brackets
arr1 = np.array([1,2,3])
arr1


array([1, 2, 3])

In [3]:
print(arr1)

[1 2 3]


In [4]:
print(type(arr1))

<class 'numpy.ndarray'>


In [6]:
print(arr1.shape)

(3,)


In [7]:
print(arr1[2])

3


In [8]:
arr1[2] = 5
arr1

array([1, 2, 5])

In [10]:
arr2 = np.array([[1,2,3],[3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [13]:
arr2[1][0]

3

In [14]:
print(arr2.shape)

(2, 3)


In [15]:
arr2[1,2]

5

In [16]:
arr2[1][-1]

5

In [17]:
arr2[0][1]

2

In [18]:
arrS = np.array(['China', 'India','USA','Mexico'])
arrS

array(['China', 'India', 'USA', 'Mexico'], dtype='<U6')

In [24]:
#np.arange() gives a range of values from 0 to 20 skipping every 2nd value
arrR = np.arange(0, 20, 2)
arrR

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [23]:
#np.arange() gives a range of values from 5 to 50 skipping every 3rd value
arrR2 = np.arange(5, 50, 3)
arrR2

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [25]:
#np.linspace() gives 20 uniform values from 0 t0 10
arrL = np.linspace(0,10, 20)
arrL

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [29]:
arrL2 = np.linspace(5,50,7)
arrL2

array([ 5. , 12.5, 20. , 27.5, 35. , 42.5, 50. ])

In [34]:
#GENERATEs 10 random values, values change each time code is run
arrR = np.random.rand(10)
arrR

array([0.30100244, 0.70696363, 0.11189582, 0.00495291, 0.20363953,
       0.08771132, 0.29553077, 0.99696011, 0.03351045, 0.62611962])

In [40]:
#generates random values in the shape given e.g (3, 4)
arrRa = np.random.rand(3,4)
arrRa

array([[0.68003083, 0.17151797, 0.95941922, 0.85914886],
       [0.37316289, 0.63813784, 0.82552166, 0.19688103],
       [0.02795662, 0.93624433, 0.70563858, 0.50490291]])

In [50]:
print(np.zeros(10))
print('/n')
print(np.zeros((2,3)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
/n
[[0. 0. 0.]
 [0. 0. 0.]]


In [53]:
print(np.ones((10,10)))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [55]:
#repeats each value of the given array 3 times
arr = [0, 1, 2]
print(np.repeat(arr, 3))

[0 0 0 1 1 1 2 2 2]


In [58]:
#repeats the entire array three times
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [61]:
#creates an identity matix
identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [62]:
#creates a matrix with a given diagonal
np.diag([1,2,3,4,5,6])

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [3]:
arrb = np.random.rand(5,5)
arrb

array([[0.31547171, 0.25759039, 0.27313467, 0.72825721, 0.59150051],
       [0.55604185, 0.90136285, 0.59771961, 0.39204829, 0.11221495],
       [0.60643742, 0.94663746, 0.13243114, 0.71195192, 0.5956287 ],
       [0.4120307 , 0.30375009, 0.72562241, 0.1212276 , 0.24520784],
       [0.16160385, 0.17319559, 0.16583556, 0.42777884, 0.14041218]])

In [65]:
#extracts the diagonal from teh given array
np.diag(arrb)

array([0.85352088, 0.78190262, 0.04907624, 0.41695811, 0.10409772])

In [66]:
#gives dimension of the array
arrb.ndim


2

In [67]:
arrb.size

25

In [68]:
arrb.shape

(5, 5)

In [70]:
#generates random integer 
np.random.randint(-10,10,4)

array([  6, -10,   9,  -1])

In [71]:
arrb+10

array([[10.85352088, 10.50447132, 10.57368199, 10.97534538, 10.45967631],
       [10.87550227, 10.78190262, 10.13072602, 10.84449912, 10.83457307],
       [10.43897617, 10.41848266, 10.04907624, 10.30192239, 10.46911794],
       [10.04335553, 10.06249248, 10.86794742, 10.41695811, 10.84051423],
       [10.25206141, 10.58980387, 10.65480306, 10.44261562, 10.10409772]])

In [72]:
arrb/2

array([[0.42676044, 0.25223566, 0.28684099, 0.48767269, 0.22983816],
       [0.43775114, 0.39095131, 0.06536301, 0.42224956, 0.41728653],
       [0.21948808, 0.20924133, 0.02453812, 0.15096119, 0.23455897],
       [0.02167777, 0.03124624, 0.43397371, 0.20847906, 0.42025711],
       [0.1260307 , 0.29490193, 0.32740153, 0.22130781, 0.05204886]])

In [73]:
arrb*2

array([[1.70704177, 1.00894263, 1.14736397, 1.95069075, 0.91935262],
       [1.75100455, 1.56380523, 0.26145205, 1.68899824, 1.66914613],
       [0.87795233, 0.83696533, 0.09815248, 0.60384478, 0.93823589],
       [0.08671106, 0.12498495, 1.73589485, 0.83391622, 1.68102845],
       [0.50412281, 1.17960773, 1.30960611, 0.88523124, 0.20819544]])

In [74]:
arrb%2

array([[0.85352088, 0.50447132, 0.57368199, 0.97534538, 0.45967631],
       [0.87550227, 0.78190262, 0.13072602, 0.84449912, 0.83457307],
       [0.43897617, 0.41848266, 0.04907624, 0.30192239, 0.46911794],
       [0.04335553, 0.06249248, 0.86794742, 0.41695811, 0.84051423],
       [0.25206141, 0.58980387, 0.65480306, 0.44261562, 0.10409772]])

In [75]:
arrb**2

array([[0.7284979 , 0.25449131, 0.32911102, 0.9512986 , 0.21130231],
       [0.76650423, 0.6113717 , 0.01708929, 0.71317876, 0.6965122 ],
       [0.19270007, 0.17512774, 0.00240848, 0.09115713, 0.22007165],
       [0.0018797 , 0.00390531, 0.75333273, 0.17385407, 0.70646417],
       [0.06353495, 0.3478686 , 0.42876704, 0.19590859, 0.01083634]])

In [76]:
np.exp(arrb)

array([[2.347899  , 1.65610973, 1.77478979, 2.65208302, 1.58356132],
       [2.40008049, 2.18562672, 1.1396555 , 2.32681207, 2.30383026],
       [1.55111832, 1.51965398, 1.05030042, 1.35245626, 1.59858353],
       [1.04430911, 1.06448645, 2.38201656, 1.51733895, 2.31755842],
       [1.28667504, 1.80363463, 1.92476341, 1.55677383, 1.10970889]])

In [77]:
np.log(arrb)

array([[-0.15838527, -0.6842443 , -0.55568007, -0.02496364, -0.77723271],
       [-0.13295753, -0.24602508, -2.03465157, -0.16901159, -0.18083498],
       [-0.82331016, -0.87111981, -3.01438025, -1.19758529, -0.75690106],
       [-3.13832099, -2.77270911, -0.14162414, -0.87476952, -0.1737414 ],
       [-1.37808255, -0.52796523, -0.42342076, -0.81505356, -2.26242522]])

In [78]:
np.sin(arrb)

array([[0.75359947, 0.48334468, 0.54272825, 0.82789565, 0.44365804],
       [0.76786536, 0.70463074, 0.13035401, 0.74763857, 0.7410099 ],
       [0.42501293, 0.40637452, 0.04905654, 0.29735619, 0.4520997 ],
       [0.04334195, 0.06245181, 0.76300377, 0.40498106, 0.74498625],
       [0.24940075, 0.55619804, 0.60900305, 0.42830449, 0.10390981]])

In [79]:
np.cos(arrb)

array([[0.65733389, 0.87543013, 0.83990836, 0.56088215, 0.89619615],
       [0.64061126, 0.70957418, 0.99146751, 0.66410584, 0.67149411],
       [0.90518728, 0.9137066 , 0.998796  , 0.95476662, 0.89196741],
       [0.9990603 , 0.99804798, 0.64639403, 0.91432508, 0.66707982],
       [0.96840036, 0.83104978, 0.79316788, 0.90363447, 0.99458672]])

In [80]:
np.tan(arrb)

array([[1.14644852, 0.55212251, 0.64617556, 1.4760599 , 0.49504569],
       [1.19864481, 0.99303323, 0.13147582, 1.12578225, 1.10352405],
       [0.46953038, 0.44475384, 0.04911568, 0.31144385, 0.50685674],
       [0.04338272, 0.06257395, 1.1804004 , 0.44292896, 1.11678726],
       [0.25753889, 0.66927162, 0.76781103, 0.47397981, 0.10447537]])

In [81]:
#sums all the values in array arrb

np.sum(arrb)

12.786123812181524

In [84]:
#sums all the values along the columns
np.sum(arrb, axis=0)

array([2.46341626, 2.35715294, 2.27623473, 2.98134061, 2.70797927])

In [85]:
#sums all the values along the rows
np.sum(arrb, axis=1)

array([3.36669587, 3.4672031 , 1.6775754 , 2.23126777, 2.04338167])

In [86]:
np.min(arrb)

0.04335553132575676

In [87]:
np.max(arrb)

0.9753453751197477

In [88]:
arrb

array([[0.85352088, 0.50447132, 0.57368199, 0.97534538, 0.45967631],
       [0.87550227, 0.78190262, 0.13072602, 0.84449912, 0.83457307],
       [0.43897617, 0.41848266, 0.04907624, 0.30192239, 0.46911794],
       [0.04335553, 0.06249248, 0.86794742, 0.41695811, 0.84051423],
       [0.25206141, 0.58980387, 0.65480306, 0.44261562, 0.10409772]])

In [89]:
#gives the minimum value along the rows
np.min(arrb, axis=0)

array([0.04335553, 0.06249248, 0.04907624, 0.30192239, 0.10409772])

In [90]:
#gives the minimum value along the columns
np.min(arrb, axis=1)

array([0.45967631, 0.13072602, 0.04907624, 0.04335553, 0.10409772])

In [11]:
#find standard deviation of arrb
np.std(arrb)

0.2504758562594793

In [12]:
#find the mean
np.mean(arrb)

0.42380373329528725

In [13]:
#find the median of arrb
np.median(arrb)

0.39204828619123044

In [14]:
#find the variance along the rows of arrb
np.var(arrb, axis=0)

array([0.02611115, 0.11265845, 0.05708562, 0.05090866, 0.04585204])

In [10]:
np.var(arrb)

0.06273815456891935

In [17]:
arrb[1:,2:4]

array([[0.59771961, 0.39204829],
       [0.13243114, 0.71195192],
       [0.72562241, 0.1212276 ],
       [0.16583556, 0.42777884]])

In [19]:
arrb[1:,2:-1]

array([[0.59771961, 0.39204829],
       [0.13243114, 0.71195192],
       [0.72562241, 0.1212276 ],
       [0.16583556, 0.42777884]])

In [23]:
np.sort(arrb, axis=1)

array([[0.25759039, 0.27313467, 0.31547171, 0.59150051, 0.72825721],
       [0.11221495, 0.39204829, 0.55604185, 0.59771961, 0.90136285],
       [0.13243114, 0.5956287 , 0.60643742, 0.71195192, 0.94663746],
       [0.1212276 , 0.24520784, 0.30375009, 0.4120307 , 0.72562241],
       [0.14041218, 0.16160385, 0.16583556, 0.17319559, 0.42777884]])

In [22]:
arrb

array([[0.31547171, 0.25759039, 0.27313467, 0.72825721, 0.59150051],
       [0.55604185, 0.90136285, 0.59771961, 0.39204829, 0.11221495],
       [0.60643742, 0.94663746, 0.13243114, 0.71195192, 0.5956287 ],
       [0.4120307 , 0.30375009, 0.72562241, 0.1212276 , 0.24520784],
       [0.16160385, 0.17319559, 0.16583556, 0.42777884, 0.14041218]])

In [24]:
#transposes the data
arrb.T

array([[0.31547171, 0.55604185, 0.60643742, 0.4120307 , 0.16160385],
       [0.25759039, 0.90136285, 0.94663746, 0.30375009, 0.17319559],
       [0.27313467, 0.59771961, 0.13243114, 0.72562241, 0.16583556],
       [0.72825721, 0.39204829, 0.71195192, 0.1212276 , 0.42777884],
       [0.59150051, 0.11221495, 0.5956287 , 0.24520784, 0.14041218]])

In [26]:
#another method for transposition
arrb.transpose()

array([[0.31547171, 0.55604185, 0.60643742, 0.4120307 , 0.16160385],
       [0.25759039, 0.90136285, 0.94663746, 0.30375009, 0.17319559],
       [0.27313467, 0.59771961, 0.13243114, 0.72562241, 0.16583556],
       [0.72825721, 0.39204829, 0.71195192, 0.1212276 , 0.42777884],
       [0.59150051, 0.11221495, 0.5956287 , 0.24520784, 0.14041218]])

In [27]:
#transposes a slice
arrb[:3,:].T

array([[0.31547171, 0.55604185, 0.60643742],
       [0.25759039, 0.90136285, 0.94663746],
       [0.27313467, 0.59771961, 0.13243114],
       [0.72825721, 0.39204829, 0.71195192],
       [0.59150051, 0.11221495, 0.5956287 ]])

In [29]:
#flattens a slice (almost like an inverse trnasposition)
arrb[:3,:].flatten()

array([0.31547171, 0.25759039, 0.27313467, 0.72825721, 0.59150051,
       0.55604185, 0.90136285, 0.59771961, 0.39204829, 0.11221495,
       0.60643742, 0.94663746, 0.13243114, 0.71195192, 0.5956287 ])

In [30]:
arr3 = np.array([4,5,6,7,8])
arr3

array([4, 5, 6, 7, 8])

In [33]:
arr4 = np.append(arr3, 8)
arr4

array([4, 5, 6, 7, 8, 8])

In [39]:
arr5 = np.insert(arr3, 0, [1,2,3])
arr5

array([1, 2, 3, 4, 5, 6, 7, 8])

In [45]:
#deletes a value
arr6 = np.delete(arr5, 0)
arr6

array([6, 7, 8, 8])

In [48]:
arrC = arr4.copy()
arrC

array([4, 5, 6, 7, 8, 8])

In [52]:
#cocatenates two arrays
arrA = np.array([[1,2,3,4],[1,2,3,4]])
arrB = np.array([[5,6,7,8],[5,6,7,8]])
arr_cat = np.concatenate((arrA,arrB),axis = 0)
print(arr_cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [53]:
#cocatenates two arrays
arrA = np.array([[1,2,3,4],[1,2,3,4]])
arrB = np.array([[5,6,7,8],[5,6,7,8]])
arr_cat = np.concatenate((arrA,arrB),axis = 1)
print(arr_cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [55]:
#stacks the array vertically
catV = np.vstack((arrA, arrB))
catV

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [56]:
#stacks the array horizontally
catH = np.hstack((arrA, arrB))
catH

array([[1, 2, 3, 4, 5, 6, 7, 8],
       [1, 2, 3, 4, 5, 6, 7, 8]])

In [58]:
arrr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(arrr)
#prints out unique values
print(np.unique(arrr))

[1 2 3 4 5 6 3 6 1 2 4]
[1 2 3 4 5 6]


In [61]:
#prints unique values and then counts number of occurences
uniques, counts = np.unique(arrr, return_counts = True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 2 1 2]


In [66]:
#intersection, differentiation, neither
arrC = np.array([1,2,3,4,5])
arrD = np.array([3,4,5,6,7])
#intersection of both arrays
print(np.intersect1d(arrC, arrD)) #where 1d is one-dimensional array
#union of both arrays
(print(np.union1d(arrC, arrD)))
print(np.setdiff1d(arrC, arrD))
print(np.setxor1d(arrC, arrD))

[3 4 5]
[1 2 3 4 5 6 7]
[1 2]
[1 2 6 7]


## SIMPLILEARN PRACTICE 2